(ns group-chat-app.ios.styles)

(def view {:flex-direction "column" :margin 40 :align-items "center"})
(def chat-view {:flex-direction "column" :margin 40})
(def headng {:font-size 30 :font-weight "100" :margin-bottom 20 :text-align "center"})
(def input {:height 30 :border-color :grey :border-width 1 :border-radius 5 :font-weight "100" :margin-bottom 5})
(def btn-disabled {:opacity 0.8})
(def btn-primary {:background-color "#577492" :padding 10 :border-radius 5 :color "white"})
(def author-name {:color "#aaaaaa" :font-size 12 :margin-left 5 :margin-top 8})
(def message-time {:color "#aaaaaa" :font-size 10 :margin-left 15 :margin-top 9})
(def message-author-avatar {:height 30 :width 30})
(def message-text-box {:background-color "#e6e6eb" :borderRadius 10 :paddingLeft 14 :paddingRight 14 :paddingBottom 10 :paddingTop 8})
(def user-avatar {:height 48 :width 48})
(def user-name {:font-size 17 :margin-left 5 :margin-top 13})